baseURL: "https://examplesite.com/"
title: Zorroware
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    title: Zorroware
    description: "Zorroware's Website"
    DateFormat: "January 2, 2006"
    defaultTheme: dark # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    label:
        text: "Home"
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Zorroware
        subtitle: >
            We are a team of FOSS developers focused on providing the best quality software we can.
            View our about page for more information.

    socialIcons:
        - name: github
          url: "https://github.com/zorroware"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

menu:
    main:
        - identifier: about
          name: About
          url: about/
          weight: 10
        - identifier: search
          name: Search
          url: search/
          weight: 20
        - identifier: posts
          name: Posts
          url: posts/
          weight: 30
        - identifier: tags
          name: Tags
          url: tags/
          weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
